[package]
name = "wavv"
version = "0.1.0"
authors = ["Samuel Leeuwenburg <samleeuwenburg@gmail.com>"]
edition = "2018"
description = "no_std library for reading wav files"
repository = "https://github.com/samuelleeuwenburg/wavv"
license = "Apache-2.0"
keywords = ["audio", "wav", "no_std"]